services:
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=user
      - MYSQL_DATABASE=django_db
volumes:
  db_data: {}